export default {
  config: {
    option: {
      siteOption1: [
        { name: '잭팟', active: true, info: '잭팟 사용여부를 선택' },
        {
          name: '환전비밀번호',
          active: true,
          info: '환전비밀번호 사용여부를 선택',
        },
        {
          name: '휴대폰인증',
          active: false,
          info: '가입시 휴대폰 SMS 인증여부를 선택',
        },
        {
          name: '전화번호삭제',
          active: false,
          info: '가입승인된 회원의 전화번호 삭제여부를 선택',
        },
        { name: '회원가입', active: true, info: '회원가입 사용여부를 선택' },
        {
          name: '쿠폰베팅',
          active: true,
          info: '쿠폰을 이용한 베팅 사용여부를 선택',
        },
        {
          name: '파트너하부생성',
          active: true,
          info: '파트너의 하부 생성여부를 선택',
        },
        {
          name: '자동발송(가입)',
          active: true,
          info: '가입시 쪽지 자동발송여부를 선택',
        },
        {
          name: '자동발송(충전)',
          active: true,
          info: '충전시 쪽지 자동발송여부를 선택',
        },
        {
          name: '자동발송(환전)',
          active: true,
          info: '환전시 쪽지 자동발송여부를 선택',
        },
        { name: '페이백', active: true, info: '페이백 사용여부를 선택' },
      ],
      siteOption2: [
        {
          name: '페이백최소금액',
          value: '',
          info: '페이백 최소 신청금액 (단위: 원)',
        },
        {
          name: '카카오톡',
          value: 'kakaotalk',
          info: '카카오톡 표시 (아이디)',
        },
        {
          name: '카카오톡링크',
          value: 'https://open.kakao.com/o/kakaotalk',
          info: '카카오톡 링크 (주소)',
        },
        { name: '텔레그램', value: 'telegram', info: '텔레그램 표시 (아이디)' },
        {
          name: '텔레그램링크',
          value: 'https://t.me/telegram',
          info: '텔레그램 링크 (주소)',
        },
        { name: '라인', value: '', info: '라인 표시 (아이디)' },
        { name: '라인링크', value: '', info: '라인 링크 (주소)' },
        {
          name: '자동로그아웃',
          value: '3600',
          info: '회원의 자동로그아웃 시간을 설정 (단위: 초)',
        },
        {
          name: '고액베팅',
          value: '1000000',
          info: '입력금액 이상을 고액베팅으로 표시 (단위: 원)',
        },
        {
          name: '고액당첨',
          value: '',
          info: '입력금액 이상을 고액당첨으로 표시 (단위: 원)',
        },
        {
          name: '최소입금액',
          value: '10000',
          info: '최소 입금액을 표시 (단위: 원)',
        },
        {
          name: '최소출금액',
          value: '20000',
          info: '최소 출금액을 표시 (단위: 원)',
        },
        {
          name: '최대보너스',
          value: '',
          info: '1회 입금시 받을 수 있는 최대 보너스 (단위: 원)',
        },
        {
          name: '1일최대보너스',
          value: '',
          info: '1일 최대로 받을 수 있는 보너스 (단위: 원)',
        },
        {
          name: '보너스최소금액',
          value: '',
          info: '입력금액 이상만 보너스로 인정 (단위: 원)',
        },
      ],
      bettingOption: {
        sportsFolder: [
          { name: '1폴더', active: false, rate: 1.01 },
          { name: '2폴더', active: false, rate: 1.02 },
          { name: '3폴더', active: true, rate: 1.03 },
          { name: '4폴더', active: false, rate: 1.04 },
          { name: '5폴더', active: true, rate: 1.05 },
          { name: '6폴더', active: false, rate: 1.06 },
          { name: '7폴더', active: true, rate: 1.07 },
          { name: '8폴더', active: false, rate: 1.08 },
          { name: '9폴더', active: false, rate: 1.09 },
          { name: '10폴더', active: false, rate: 1.1 },
        ],
        sportsInsurance: { active: true, minFolder: 8, allowedFolders: 0 },
        minigameInsurance: { active: true, allowedFolders: 0 },
        axis: { active: true, minFolder: 8, allowedFolders: 0 },
        bettingCancel: { active: true, allowedTime: 60, allowedDay: 3 },
        beforeStartCancel: { active: true, allowedTime: 300, allowedDay: 3 },
      },
      depositBonus: [
        {
          no: 1,
          name: '5% 보너스',
          rate: 5,
          startTime: '00:00',
          endTime: '23:59',
          automatic: '사용',
          sports1: 150,
          sports2: 100,
          sports3: 100,
          casino: 100,
          minigame: 200,
        },
        {
          no: 2,
          name: '10% 보너스',
          rate: 10,
          startTime: '00:00',
          endTime: '23:59',
          automatic: '사용',
          sports1: 300,
          sports2: 200,
          sports3: 100,
          casino: 200,
          minigame: 350,
        },
        {
          no: 3,
          name: '심야(15%)',
          rate: 15,
          startTime: '03:00',
          endTime: '06:00',
          automatic: '사용',
          sports1: 300,
          sports2: 200,
          sports3: 100,
          casino: 300,
          minigame: 350,
        },
        {
          no: 4,
          name: '돌발(20%)',
          rate: 20,
          startTime: '18:00',
          endTime: '21:00',
          automatic: '사용',
          sports1: 300,
          sports2: 200,
          sports3: 100,
          casino: 400,
          minigame: 400,
        },
      ],
      gameEndtime: [
        { gameName: '스포츠', endTime: 180 },
        { gameName: '가상축구', endTime: 20 },
        { gameName: '가상경마', endTime: 20 },
        { gameName: '가상개경주', endTime: 20 },
        { gameName: '하이로우', endTime: 30 },
        { gameName: '바카라', endTime: 30 },
        { gameName: '파워볼', endTime: 30 },
        { gameName: '파워사다리', endTime: 30 },
        { gameName: '키노사다리', endTime: 30 },
        { gameName: '파워프리킥', endTime: 30 },
        { gameName: '스피드홈런', endTime: 30 },
        { gameName: '파워스피드덩크', endTime: 30 },
        { gameName: '환율', endTime: 30 },
        { gameName: '비트코인', endTime: 30 },
        { gameName: '금', endTime: 30 },
        { gameName: '유가', endTime: 30 },
      ],
      siteDisplay: [
        { name: '충전', visible: true },
        { name: '환전', visible: true },
        { name: '고객센터', visible: true },
        { name: '공지사항', visible: true },
        { name: '이벤트', visible: true },
        { name: '자유게시판', visible: true },
        { name: '실시간출금현황', visible: false },
        { name: '주간출금랭킹', visible: false },
        { name: '롤링이벤트당첨자', visible: false },
        { name: '잭팟이벤트당첨자', visible: false },
        { name: '스포츠', visible: true },
        { name: '라이브스포츠', visible: true },
        { name: '가상스포츠', visible: true },
        { name: '라이브카지노', visible: true },
        { name: '하이로우', visible: true },
        { name: '바카라', visible: true },
        { name: '미니게임', visible: true },
        { name: '차트게임', visible: true },
      ],
      forbiddenWord: '',
      emergency: {
        active: true,
        context: '',
      },
    },
    level: {
      levelOption: [
        {
          level: 1,
          display: 1,
          context: '신규레벨',
          autoLevelUp: {
            active: true,
            duringDate: 90,
            depositCnt: 10,
            depositAmount: 500000,
            boardCnt: 3,
          },
          articleWrite: {
            cnt: 3,
            point: 300,
            time: 50,
          },
          replyWrite: {
            cnt: 3,
            point: 300,
            time: 50,
          },
          prohibition: {
            prematch: 3,
            live: 3,
          },
          payback: {
            ratio: 3,
            maxAmount: 40000,
          },
          deduction: {
            one: 0.02,
            two: 0.02,
            three: 0.02,
            four: 0.02,
            five: 0.02,
          },
          friend: {
            active: true,
            depositStatus: {
              active: true,
              ratio: 40,
            },
            paybackStatus: true,
          },
          sportsInsurance: {
            active: true,
            folders: 8,
            cnt: 2,
          },
          sportsBase: {
            active: true,
            folders: 8,
            cnt: 2,
          },
          banks: {
            auto: true,
            account: '1231231231',
            name: '국민은행',
            owner: '김정식',
            memo: '테스트',
          },
        },
      ],
    },
    bank: [
      {
        name: '농협',
        context:
          '매일 : 23:55 - 00:35 (정기 점검 : 매월 3째주 월요일 00:00 - 04:00)',
        active: true,
      },
    ],
    denyIp: [],
  },
  sportConfig: {
    combination: [],
    common: {
      base: 2,
    },
    insureBetting: {},
    receiveOption: {
      base: {
        sports: {
          active: true,
          setTime: '12:00',
        },
        locations: {
          active: true,
          setTime: '12:00',
        },
        leagues: {
          active: true,
          setTime: '12:00',
        },
        markets: {
          active: true,
          setTime: '12:00',
        },
      },
    },
  },
  adminConfig: {
    denyIp: [],
    allowIp: [],
  },
};
